[package]
name = "concurrenciapythonrustr"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "concurrenciapythonrustr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
rayon = "1.8"